<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Broadcasting</a></span><ul class="toc-item"><li><span><a href="#Sorting" data-toc-modified-id="Sorting-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Sorting</a></span></li></ul></li><li><span><a href="#Messing-Around" data-toc-modified-id="Messing-Around-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Messing Around</a></span></li></ul></div>

In [1]:
import numpy as np

In [2]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
arr.reshape((4,2)).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
arr.reshape((4,2)).flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
arr.reshape((2,4)).ravel('F')

array([0, 4, 1, 5, 2, 6, 3, 7])

In [6]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])

arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [7]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
arr = np.arange(3)
arr.repeat([1,3,4])

array([0, 1, 1, 1, 2, 2, 2, 2])

In [9]:
arr = np.random.randn(2,2)

arr.repeat([1,2], axis=0) # repeat row #1 2wice.

array([[ 0.76762368,  2.74249358],
       [ 0.18112776, -0.07374639],
       [ 0.18112776, -0.07374639]])

In [10]:
np.tile(arr, (2,1))

array([[ 0.76762368,  2.74249358],
       [ 0.18112776, -0.07374639],
       [ 0.76762368,  2.74249358],
       [ 0.18112776, -0.07374639]])

In [11]:
arr = np.arange(10) * 100

arr.take([7,1,4,2])

array([700, 100, 400, 200])

## Broadcasting

In [12]:
arr = np.random.randn(4,3)
row_means = arr.mean(1)

#de-mean
arr - row_means.reshape(4,1)

array([[ 0.93712284,  0.43475253, -1.37187536],
       [-0.24641727, -0.27618746,  0.52260473],
       [-1.23002072,  0.39490902,  0.8351117 ],
       [-0.16752621,  0.06791818,  0.09960803]])

In [16]:
arr = np.zeros((4,4))
arr_3d = arr[:, np.newaxis,:]
arr_3d

array([[[ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.]]])

In [17]:
np.random.normal(size=3)[:, np.newaxis]

array([[-0.62741321],
       [-1.05137797],
       [-2.02452188]])

In [18]:
arr = np.random.randn(3,4,5)
arr.mean(2)

array([[-0.49708641, -0.34036907,  0.27356218, -0.04948725],
       [ 0.35198726, -0.06009547, -0.02096974, -0.55058304],
       [ 0.27285109,  0.65753598,  0.11740081, -0.13512178]])

In [19]:
arr.mean((2,1))

array([-0.15334514, -0.06991525,  0.22816652])

In [20]:
arr = np.zeros((4,3))
arr[:] = 5
arr

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [21]:
col = np.array([1.25, -.42, .44, 1.6])
arr[:] = col[:, np.newaxis]
arr

array([[ 1.25,  1.25,  1.25],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [22]:
arr[:2] = [[-1.37], [.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

In [23]:
arr = np.random.randn(5,5)
arr

array([[ 1.05455344,  0.04885345, -0.5230667 , -0.02162334,  0.18674269],
       [-0.52057608, -1.06214431,  0.90198808,  0.19155757,  0.18979039],
       [-0.89528454, -0.30801208, -0.76541136, -1.18318569, -0.70279374],
       [-0.79487601, -0.06847925, -0.39389312, -1.32270229,  0.65338804],
       [ 0.04704659, -0.75476822,  0.29016631,  0.22368094,  0.57448002]])

In [24]:
arr[::2]

array([[ 1.05455344,  0.04885345, -0.5230667 , -0.02162334,  0.18674269],
       [-0.89528454, -0.30801208, -0.76541136, -1.18318569, -0.70279374],
       [ 0.04704659, -0.75476822,  0.29016631,  0.22368094,  0.57448002]])

In [25]:
arr[::2].sort(1)
arr

array([[-0.5230667 , -0.02162334,  0.04885345,  0.18674269,  1.05455344],
       [-0.52057608, -1.06214431,  0.90198808,  0.19155757,  0.18979039],
       [-1.18318569, -0.89528454, -0.76541136, -0.70279374, -0.30801208],
       [-0.79487601, -0.06847925, -0.39389312, -1.32270229,  0.65338804],
       [-0.75476822,  0.04704659,  0.22368094,  0.29016631,  0.57448002]])

In [26]:
arr[:,:-1] < arr[:,1:]

array([[ True,  True,  True,  True],
       [False,  True, False, False],
       [ True,  True,  True,  True],
       [ True, False, False,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [27]:
#nested dtypes are possible...
sarr = np.array([(1.5,6), (np.pi, -2)],
                dtype = [('x', np.float64), ('y', np.int32)])
sarr

array([( 1.5       ,  6), ( 3.14159265, -2)], 
      dtype=[('x', '<f8'), ('y', '<i4')])

In [28]:
sarr[0]['y']

6

### Sorting

In [29]:
arr[:,0].sort()
arr

array([[-1.18318569, -0.02162334,  0.04885345,  0.18674269,  1.05455344],
       [-0.79487601, -1.06214431,  0.90198808,  0.19155757,  0.18979039],
       [-0.75476822, -0.89528454, -0.76541136, -0.70279374, -0.30801208],
       [-0.5230667 , -0.06847925, -0.39389312, -1.32270229,  0.65338804],
       [-0.52057608,  0.04704659,  0.22368094,  0.29016631,  0.57448002]])

In [30]:
values = np.array([5, 33, 21, 3])
indexer = values.argsort()

indexer

array([3, 0, 2, 1])

In [31]:
X = np.random.randn(4,4)

Xm = np.matrix(X)

Xm

matrix([[ 0.17176272, -1.16839375,  1.13899503, -1.05754939],
        [ 0.56585814, -1.94849641, -0.16916671, -1.36856668],
        [-0.98236802,  0.22938504, -0.07357266,  0.88319526],
        [ 0.01430566,  0.44063014, -0.54242981,  1.80176498]])

In [32]:
# *not* one dimensional!
ym = Xm[:,0]
ym

matrix([[ 0.17176272],
        [ 0.56585814],
        [-0.98236802],
        [ 0.01430566]])

In [33]:
ym.T * Xm * ym

matrix([[-0.82279355]])

## Messing Around

In [34]:
np.ones(2,3)

TypeError: data type not understood