In [1]:
import numpy as np

In [2]:
arr = np.array([6, 7.5, 8, 0, 1])
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [3]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2.dtype

dtype('int64')

In [5]:
arrz = np.zeros((2,3))

In [6]:
arro = np.ones_like(arrz)
arro

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [7]:
arr2.dtype

dtype('int64')

In [8]:
arr2 = arr2.astype(np.float64)
1/arr2

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])

In [9]:
arr2 ** .5

array([[ 1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.44948974,  2.64575131,  2.82842712]])

In [10]:
arr

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [11]:
arr_view = arr[0:2]
arr_view

array([ 6. ,  7.5])

In [12]:
arr_view[0] = 4

In [13]:
arr

array([ 4. ,  7.5,  8. ,  0. ,  1. ])

In [14]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

In [15]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr3d[:,0]

array([[1, 2, 3],
       [7, 8, 9]])

In [18]:
arr3d[:,:,0]

array([[ 1,  4],
       [ 7, 10]])

In [19]:
arr3d[:,:,0] = 99
arr3d

array([[[99,  2,  3],
        [99,  5,  6]],

       [[99,  8,  9],
        [99, 11, 12]]])

In [20]:
arr3d[:1,:,:1]

array([[[99],
        [99]]])

In [21]:
names = np.array(['a', 'b', 'cee', 'dee', 'eff', 'gee'])
data = np.random.randn(7,4)

In [22]:
names

array(['a', 'b', 'cee', 'dee', 'eff', 'gee'], 
      dtype='|S3')

In [23]:
data

array([[ 1.15063543, -0.6918197 ,  0.23432949,  0.44191408],
       [-0.02926242, -1.48851629,  0.72112534, -0.09175716],
       [-0.32552025, -0.09229452, -1.24731167,  0.70451491],
       [ 0.89926414,  0.2667176 ,  0.8328177 , -0.58289382],
       [ 0.97874234, -0.43578661,  0.97106291, -0.13567529],
       [ 0.04898338,  0.63545303,  0.7198794 ,  0.46928645],
       [ 2.08860894, -1.05331256, -0.58288127,  0.72451786]])

In [24]:
data[names=='b']

array([[-0.02926242, -1.48851629,  0.72112534, -0.09175716]])

In [25]:
data[data<0] = 0
data

array([[ 1.15063543,  0.        ,  0.23432949,  0.44191408],
       [ 0.        ,  0.        ,  0.72112534,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.70451491],
       [ 0.89926414,  0.2667176 ,  0.8328177 ,  0.        ],
       [ 0.97874234,  0.        ,  0.97106291,  0.        ],
       [ 0.04898338,  0.63545303,  0.7198794 ,  0.46928645],
       [ 2.08860894,  0.        ,  0.        ,  0.72451786]])

In [26]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i

arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [27]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [28]:
arr[[-5, -3, -7]]

array([[ 3.,  3.,  3.,  3.],
       [ 5.,  5.,  5.,  5.],
       [ 1.,  1.,  1.,  1.]])

In [29]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [30]:
arr[range(4), range(4)]

array([ 0,  5, 10, 15])

In [31]:
arr[np.ix_(range(4), range(4))]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
arr = np.arange(10)
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [33]:
points = np.arange(-5,5,.01)
xs, ys = np.meshgrid(points, points)

xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ..., 
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [34]:
z = np.sqrt(xs**2 + ys**2)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.show()

In [36]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array(np.arange(2.1, 2.6, .1))
yarr

array([ 2.1,  2.2,  2.3,  2.4,  2.5])

In [41]:
cond = np.array([1, 0, 1, 1, 0])
res1 = [(x if c else y) for x,y,c in zip(xarr, yarr, cond)] #compare to
res2 = np.where(cond, xarr, yarr)

res1 == res2

array([ True,  True,  True,  True,  True], dtype=bool)

In [49]:
from numpy.linalg import inv, qr
from numpy.random import randn

X = randn(5,5)

inv(X.T.dot(X))

array([[ 2.09104776,  1.2723538 , -0.62713   , -0.07922417, -0.61212032],
       [ 1.2723538 ,  2.01850349, -0.55636412, -0.04427985, -0.85698443],
       [-0.62713   , -0.55636412,  0.32463543,  0.11000499,  0.21890045],
       [-0.07922417, -0.04427985,  0.11000499,  0.24762186, -0.10891002],
       [-0.61212032, -0.85698443,  0.21890045, -0.10891002,  0.5767356 ]])

In [51]:
# simulate a random walk...
# regular Python
import random
position = 0
walk = [position]
steps = 1000
for i in xrange(steps):
    step = 1 if random.randint(0,1) else -1
    position += step
    walk.append(position)
    
# now np...
nsteps = 1000
draws = np.random.randint(0,2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [56]:
# first crossing time of 10 units +/- origin...
(np.abs(walk) >= 10).argmax()

61

In [58]:
# many walks at once...

nwalks=5000; nsteps=100

draws = np.random.randint(0,2,size=(nwalks,nsteps))
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)  # along first (not 0th) axis

walks.max()
walks.min()

-39

In [60]:
# crossing time to +/- 30

hits30 = (np.abs(walks) >= 30).any(1)
hits30.sum()

32

In [61]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

85.1875

In [65]:
(np.abs(walks[hits30]) >= 30)[0,:].argmax()

83